'\" t
.\"     Title: koha-upgrade-schema
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 09/25/2011
.\"    Manual: koha-upgrade-schema
.\"    Source: Koha
.\"  Language: English
.\"
.TH "KOHA\-UPGRADE\-SCHEM" "8" "09/25/2011" "Koha" "koha-upgrade-schema"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
koha-upgrade-schema \- Upgrade the DB schema for Koha instances\&. Done automatically on package upgrades\&.
.SH "SYNOPSIS"
.HP \w'\fBkoha\-upgrade\-schema\fR\ 'u
\fBkoha\-upgrade\-schema\fR {\fIinstancename\fR...}
.SH "DESCRIPTION"
.PP
Upgrade the DB schema for Koha instances\&. Done automatically on package upgrades\&.
.SH "SEE ALSO"
\fBkoha\-dump\-defaults(8)\fR, \fBkoha\-mysql(8)\fR, \fBkoha\-reset\-passwd(8)\fR
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
