'\" t
.\"     Title: koha-restore
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 09/25/2011
.\"    Manual: koha-restore
.\"    Source: Koha
.\"  Language: English
.\"
.TH "KOHA\-RESTORE" "8" "09/25/2011" "Koha" "koha-restore"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
koha-restore \- Restore a Koha site from a dump (from koha\-dump)\&.
.SH "SYNOPSIS"
.HP \w'\fBkoha\-restore\fR\ 'u
\fBkoha\-restore\fR {\fBsqldump\fR} {\fBconfigdump\fR}
.SH "DESCRIPTION"
.PP
Restore a Koha site from a dump (from koha\-dump)\&.
.SH "SEE ALSO"
\fBkoha\-disable(8)\fR, \fBkoha\-dump(8)\fR, \fBkoha\-enable(8)\fR, \fBkoha\-remove(8)\fR
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
