'\" t
.\"     Title: koha-foreach
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 09/25/2011
.\"    Manual: koha-foreach
.\"    Source: Koha
.\"  Language: English
.\"
.TH "KOHA\-FOREACH" "8" "09/25/2011" "Koha" "koha-foreach"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
koha-foreach \- Run a command for each Koha instance\&. Takes the same arguments as koha\-list\&.
.SH "SYNOPSIS"
.HP \w'\fBkoha\-list\fR\ 'u
\fBkoha\-list\fR [\fB\-\-enabled\fR] [\fB\-\-email\fR|\fB\-\-noemail\fR] [\fBcommand\fR]
.SH "DESCRIPTION"
.PP
Run a command for each Koha instance\&. Takes the same arguments as koha\-list\&.
.SH "SEE ALSO"
\fBkoha\-create\-dirs(8)\fR, \fBkoha\-list(8)\fR
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
